### ISSUE TITLE
Uncaught Error: Cannot find module 'svelte/store'

### ISSUE THREAD

**Issue by Arturexe** [inertiajs/inertia-laravel#394]
I've followed the steps in [inertiajs.com](https://inertiajs.com/) to set up laravel, inertia and svelte but when I spin up a php server, these errors are shown in the browser:

```
Uncaught Error: Cannot find module 'svelte/store'
    at webpackMissingModule (app.js:200:50)
    at Module../node_modules/@inertiajs/inertia-svelte/src/store.js (app.js:200:137)
    at __webpack_require__ (app.js:7495:42)
    at Module../node_modules/@inertiajs/inertia-svelte/src/page.js (app.js:177:64)
    at __webpack_require__ (app.js:7495:42)
    at Module../node_modules/@inertiajs/inertia-svelte/src/index.js (app.js:90:63)
    at __webpack_require__ (app.js:7495:42)
    at Module../resources/js/app.js (app.js:2562:83)
    at __webpack_require__ (app.js:7495:42)
    at app.js:7660:64
```

`app.js`:
```

import { createInertiaApp } from '@inertiajs/inertia-svelte'
import { InertiaProgress } from '@inertiajs/progress'

InertiaProgress.init()

createInertiaApp({
    resolve: name => require(`./Pages/${name}.svelte`),
    setup({ el, App, props }) {
        new App({ target: el, props })
    },
})
```

`webpack.mix.js`:
```

const mix = require('laravel-mix');
const path = require('path');

mix.js('resources/js/app.js', 'public/js')
    .postCss("resources/css/app.css", "public/css")
    .browserSync('127.0.0.1:8000');
```

`web.php`:
```
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return inertia('app');
});
```

`app.blade.php`:
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
  <link href="{{ mix('/css/app.css') }}" rel="stylesheet" />
  <script src="{{ mix('/js/app.js') }}" defer></script>
  @inertiaHead
</head>
<body>
  @inertia
</body>
</html>
```

`views/Pages/app.svelte`:
```
<p>This is a svelte component.</p>
```

**Comment by Arturexe** [comment]
I've moved the problem to inertiajs/inertia (svelte)
