### ISSUE TITLE
Can't find module when run 'node ssr.js'

### ISSUE THREAD

**Issue by boxshadow** [inertiajs/inertia-laravel#461]
need help

when I run server-side-render
and request the laravel route

node output info
```
node public/asserts/js/ssr.js
Starting SSR server on port 13714...
Inertia SSR server started.
Event/Show
Error: Cannot find module '../../../asserts/js/194.js'
Require stack:
- /Users/qiaobin/PhpstormProjects/tdd-learn/public/asserts/js/ssr.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.n.f.require (/Users/qiaobin/PhpstormProjects/tdd-learn/public/asserts/js/ssr.js:1:1305)
    at /Users/qiaobin/PhpstormProjects/tdd-learn/public/asserts/js/ssr.js:1:836
    at Array.reduce (<anonymous>)
    at Function.n.e (/Users/qiaobin/PhpstormProjects/tdd-learn/public/asserts/js/ssr.js:1:814)
    at o (/Users/qiaobin/PhpstormProjects/tdd-learn/public/asserts/js/ssr.js:1:265)
    at resolve (/Users/qiaobin/PhpstormProjects/tdd-learn/public/asserts/js/ssr.js:1:1592) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/qiaobin/PhpstormProjects/tdd-learn/public/asserts/js/ssr.js'
  ]
}
```

webpack.mix.ssr.js
```
const path = require('path')
const mix = require('laravel-mix')
const webpackNodeExternals = require('webpack-node-externals')

mix
    .options({ manifest: false })
    .js('resources/js/ssr.js', 'public/asserts/js')
    .vue({ version: 3, options: { optimizeSSR: true } })
    .alias({ '@': path.resolve('resources/js') })
    .webpackConfig({
        target: 'node',
        externals: [webpackNodeExternals()],
    })
    .options({ manifest: false })
```
194.js is in public/asserts/js

**Comment by reinink** [comment]
Hey I'd recommend asking this question on our [Discord channel](https://discord.gg/inertiajs) or [GitHub Discussions](https://github.com/inertiajs/inertia/discussions), as this doesn't appear to be an actual bug with this library. Good luck! 👍
